apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-v1
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v1
  template:
    metadata:
      labels:
        app: greeter
        version: v1
        service: greeter
    spec:
      containers:
        - name: greeter
          image: azska/greeter:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: greet_message
              value: "Hello from Greeter v1!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-v2
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v2
  template:
    metadata:
      labels:
        app: greeter
        version: v2
        service: greeter
    spec:
      containers:
        - name: greeter
          image: azska/greeter:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: greet_message
              value: "Greetings from Greeter v2!"