apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: greeter-route
  namespace: exercises
spec:
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: greeter-v1-service
          port: 80
          weight: 75
        - name: greeter-v2-service
          port: 80
          weight: 25