apiVersion: v1
kind: Service
metadata:
  name: greeter-v1-service
  namespace: exercises
  labels:
    app: greeter
    version: v1
spec:
  type: ClusterIP
  selector:
    app: greeter
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-v2-service
  namespace: exercises
  labels:
    app: greeter
    version: v2
spec:
  type: ClusterIP
  selector:
    app: greeter
    version: v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-service
  namespace: exercises
  labels:
    app: greeter
spec:
  type: ClusterIP
  selector:
    app: greeter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080