apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-app
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-app
  template:
    metadata:
      labels:
        app: wiki-app
    spec:
      initContainers:
        - name: wiki-init
          image: azska/wiki_init:latest
          volumeMounts:
            - name: wiki-content
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wiki-content
              mountPath: /usr/share/nginx/html
        - name: wiki-sidecar
          image: azska/wiki_sidecar:latest
          volumeMounts:
            - name: wiki-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: wiki-content
          emptyDir: {}