apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wiki-route
  namespace: exercises
spec:
  parentRefs:
    - name: wiki-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: wiki-app-service
          port: 80