apiVersion: v1
kind: Service
metadata:
  name: wiki-app-service
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: wiki-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80