apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ping-pong-cpu-analysis
  namespace: exercises
spec:
  metrics:
  - name: cpu-usage
    interval: 1m
    successCondition: "result[0] <= 500"
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
        query: |
          sum(rate(container_cpu_usage_seconds_total{namespace="exercises",container!="POD",container!="",pod!=""}[5m]))