apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-service
spec:
  type: LoadBalancer
  selector:
    app: ping-pong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002