[project]
name = "dvk_project"
version = "1.2"
description = "Todo App for DevOps with Kubernetes course"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.0",
    "uvicorn>=0.35.0",
]
