apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: todo-app-backend-configmap
data:
  SERVER_PORT: "8001"
  DB_CONNECTIONS_STRING: "postgres://admin@project-postgres-svc.project:5432/project_app"