apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: todo-app-frontend-configmap
data:
  SERVER_PORT: "8000"
  IMAGE_CACHE_FOLDER: "/tmp/todo_app_images/"
  BACKEND_ADDRESS: "http://todo-app-backend-service.project:80/todos"