apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-app-frontend
    spec:
      volumes:
      - name: cache-folder
        persistentVolumeClaim:
            claimName: todo-app-pvc
      containers:
        - name: todo-app-frontend
          image: azska/dvk_project_frontend:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: cache-folder
            mountPath: /tmp/todo_app_images/
          ports:
           - containerPort: 8000
          envFrom:
            - configMapRef:
                name: todo-app-frontend-configmap
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi