apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - namespace.yaml
  - db.yaml
  - config_backend.yaml
  - config_frontend.yaml
  - deployment_backend.yaml
  - deployment_frontend.yaml
  - service_backend.yaml
  - service_frontend.yaml
  - persistent_volume_claim.yml
  - cronjob.yaml
  - gateway.yml
  - route.yml
