apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-app-cronjob
spec:
  schedule: "0 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: azska/dvk_project_cronjob
            env:
            - name: TARGET_KEY
              valueFrom:
                configMapKeyRef:
                  name: todo-app-frontend-configmap
                  key: BACKEND_ADDRESS
            - name: SOURCE_KEY
              value: "https://en.wikipedia.org/wiki/Special:Random"
          restartPolicy: OnFailure