auth:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: prometheus
  image:
    repository: bitnamilegacy/nats-exporter
    registry: docker.io
image:
  registry: docker.io
  repository: bitnamilegacy/nats
  tag: 2.11.8-debian-12-r0
global:
  security:
    allowInsecureImages: true