apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: shared-folder
        persistentVolumeClaim:
            claimName: log-output-pvc
      - name: config-file
        configMap:
          name: logoutput-configmap
      containers:
        - name: log-output
          image: azska/log_output_server:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-folder
            mountPath: /tmp/
          - name: config-file
            mountPath: /opt/
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: logoutput-configmap
                key: MESSAGE
          - name: ping_pong_url
            valueFrom:
              configMapKeyRef:
                name: logoutput-configmap
                key: ping_pong_url
          - name: file_path
            valueFrom:
              configMapKeyRef:
                name: logoutput-configmap
                key: file_path
          - name: configurated_file
            valueFrom:
              configMapKeyRef:
                name: logoutput-configmap
                key: configurated_file
        - name: log-generator
          image: azska/log_output_generator:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-folder
            mountPath: /tmp/