apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: shared-folder
        persistentVolumeClaim:
            claimName: ping-pong-pvc
      - name: config-file
        configMap:
          name: logoutput-configmap
      containers:
        - name: log-output
          image: azska/log_output_server:2.5
          volumeMounts:
          - name: shared-folder
            mountPath: /tmp/
          - name: config-file
            mountPath: /opt/
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: logoutput-configmap
                key: MESSAGE
        - name: log-generator
          image: azska/log_output_generator:1.10
          volumeMounts:
          - name: shared-folder
            mountPath: /tmp/