apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: log-output-service
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 8001