apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: log-output-service
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001