apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-broadcaster-deployment
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: IS_DEBUG
              value: "true"