apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

patches:
  - path: cronjob-patch.yaml
  - path: broadcaster-patch.yaml

images:
- name: azska/dvk_project_backend
  newName: azska/dvk_project_backend
  newTag: "4.6"
- name: azska/dvk_project_broadcaster
  newName: azska/dvk_project_broadcaster
  newTag: 0e646e220338c60768429f9e588f0b1658a513e1
- name: azska/dvk_project_cronjob
  newName: azska/dvk_project_cronjob
  newTag: latest
- name: azska/dvk_project_frontend
  newName: azska/dvk_project_frontend
  newTag: "4.5"