name: Deploy todo application

on:
  push:
    paths-ignore:
      - 'README.md'
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  BRANCH: ${{ github.ref_name }}

  FRONTEND_IMAGE: dvk_project_frontend
  BACKEND_IMAGE: dvk_project_backend

jobs:
  build-publish-deploy:
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: dwk_gke

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Set Up Google Cloud Service Account"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: "gke-gcloud-auth-plugin"

      - name: "Get GKE Credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ vars.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ vars.GKE_ZONE }}"

      - name: "Configure Docker for Artifact Registry"
        run: gcloud auth configure-docker "${{ vars.REGISTRY }}"

      - name: "Prepare image tags"
        run: |
          echo "FRONTEND_IMAGE_TAG=${{ vars.REGISTRY }}/${{ env.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ env.FRONTEND_IMAGE }}:${{ env.BRANCH }}-${{ github.sha }}" >> $GITHUB_ENV
          echo "BACKEND_IMAGE_TAG=${{ vars.REGISTRY }}/${{ env.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ env.BACKEND_IMAGE }}:${{ env.BRANCH }}-${{ github.sha }}" >> $GITHUB_ENV

      - name: "Build and Push Frontend"
        run: |
          echo "Frontend image: $FRONTEND_IMAGE_TAG"
          cd ./project/
          docker build -f Dockerfile.frontend -t $FRONTEND_IMAGE_TAG .
          docker push $FRONTEND_IMAGE_TAG

      - name: "Build and Push Backend"
        run: |
          echo "Backend image: $BACKEND_IMAGE_TAG"
          cd ./project/
          docker build -f Dockerfile.backend -t $BACKEND_IMAGE_TAG .
          docker push $BACKEND_IMAGE_TAG

      - name: "Set up kustomize"
        uses: syntaqx/setup-kustomize@v1

      - name: "Set target namespace"
        run: |
          if [ ${{ env.BRANCH }} = "master" ]; then
            echo "NAMESPACE=project" >> $GITHUB_ENV
          else
            echo "NAMESPACE=development-${{ env.BRANCH }}" >> $GITHUB_ENV
          fi
          
      - name: Deploy
        run: |
          cd ./project/manifests
          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image azska/dvk_project_backend:latest=$BACKEND_IMAGE_TAGg
          kustomize edit set image azska/dvk_project_frontend:latest=$FRONTEND_IMAGE_TAG
          kustomize build . | kubectl apply -f -
