name: GitOps Pipeline (Production) for ToDo App (project)

on:
  push:
    tags: [ 'v*' ]
    paths:
      - "project/**"
      - "!project/manifests/**"

env:
  FRONTEND_IMAGE: dvk_project_frontend
  BACKEND_IMAGE: dvk_project_backend
  CRONJOB_IMAGE: dvk_project_cronjob
  BROADCASTER_IMAGE: dvk_project_broadcaster
  TARGET_OVERLAY: production

concurrency:
  group: gitops-pipeline
  cancel-in-progress: true

jobs:
  publish-images:
    name: Build and Publish Images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: dwk_gke

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Checkout config repository
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.CONFIG_REPO }}
          ref: main
          token: ${{ secrets.GIT_TOKEN }}
          path: config-repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: "Prepare image tags"
        run: |
          echo "FRONTEND_IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}" >> $GITHUB_ENV
          echo "BACKEND_IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}" >> $GITHUB_ENV
          echo "CRONJOB_IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CRONJOB_IMAGE }}:${{ github.sha }}" >> $GITHUB_ENV
          echo "BROADCASTER_IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BROADCASTER_IMAGE }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Detect changes and build images
        run: |
          echo "Building frontend image..."
          docker buildx build --file ./project/Dockerfile.frontend \
            --tag ${{ env.FRONTEND_IMAGE_TAG }} --push ./project
          echo "Building backend image..."
          docker buildx build --file ./project/Dockerfile.backend \
            --tag ${{ env.BACKEND_IMAGE_TAG }} --push ./project
          echo "Building cronjob image..."
          docker buildx build --file ./project/Dockerfile.cronjob \
            --tag ${{ env.CRONJOB_IMAGE_TAG }} --push ./project
          echo "Building broadcaster image..."
          docker buildx build --file ./project/Dockerfile.broadcaster \
            --tag ${{ env.BROADCASTER_IMAGE_TAG }} --push ./project

      - name: Update config repository
        run: |
          cd config-repo
          cd overlays/${{ env.TARGET_OVERLAY }}
          kustomize edit set image azska/dvk_project_frontend=${{ env.FRONTEND_IMAGE_TAG }}
          kustomize edit set image azska/dvk_project_backend=${{ env.BACKEND_IMAGE_TAG }}
          kustomize edit set image azska/dvk_project_cronjob=${{ env.CRONJOB_IMAGE_TAG }}
          kustomize edit set image azska/dvk_project_broadcaster=${{ env.BROADCASTER_IMAGE_TAG }}

      - name: Commit kustomization.yaml to config repository
        uses: EndBug/add-and-commit@v9
        with:
          cwd: config-repo
          add: "overlays/${{ env.TARGET_OVERLAY }}/kustomization.yaml"
          message: "Update production image tags for Project components ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}