apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-controller-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite-controller
  template:
    metadata:
      labels:
        app: dummysite-controller
    spec:
      tolerations:
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
        effect: NoSchedule
      serviceAccountName: dummysite-controller-account
      containers:
        - name: dummysite-controller
          image: azska/dummy_site_crd:5.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"